[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/wandbox/*"
  to = "https://wandbox.org/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
